version: "3"
services:

  api:
    image: api_espera_hospital:1.0
    container_name: api_espera_hospital
    networks:
      - net_app_espera_hospital
    ports:
      - 3000:3000

  app:
    image: app_espera_hospital:1.0
    container_name: app_espera_hospital
    networks:
      - net_app_espera_hospital
    ports:
      - 8080:8080

networks:
  net_app_espera_hospital:
    driver: bridge